import { nowIso, type BriefKind } from '@lance/shared';
import type { ApiDeps } from '../deps.js';
import { shiftLocalDays, startOfLocalDay, startOfNamedLocalDay } from '../status.js';
import { toBriefView, type BriefView } from './view.js';

/**
 * The Today page's reads (spec 10 and spec 12, Today row): the newest brief
 * of a kind for a local day, the history behind it, and one brief by id.
 * Read-only: the briefs themselves are generated by the worker.
 */

export type BriefDeps = Pick<ApiDeps, 'briefs' | 'config' | 'now'>;

export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;

export interface LatestBriefInput {
  kind: BriefKind;
  /** `YYYY-MM-DD` in `config.timeZone`. Defaults to today there. */
  date?: string | undefined;
}

/**
 * The newest brief of `kind` generated on the local day. A day rather than
 * simply the newest row, so opening Today at 06:00 shows nothing rather
 * than yesterday's brief dressed as this morning's.
 */
export async function latestBrief(
  deps: BriefDeps,
  input: LatestBriefInput,
): Promise<BriefView | null> {
  const timeZone = deps.config.timeZone;
  const from =
    input.date === undefined
      ? startOfLocalDay(new Date((deps.now ?? nowIso)()), timeZone)
      : startOfNamedLocalDay(input.date, timeZone);
  const record = await deps.briefs.latest({
    kind: input.kind,
    from,
    to: shiftLocalDays(from, 1, timeZone),
  });
  return record === null ? null : toBriefView(record);
}

export interface ListBriefsInput {
  kind?: BriefKind | undefined;
  limit?: number | undefined;
  cursor?: string | undefined;
}

export interface BriefPage {
  items: BriefView[];
  nextCursor: string | null;
}

export async function listBriefs(deps: BriefDeps, input: ListBriefsInput): Promise<BriefPage> {
  const size = Math.min(input.limit ?? DEFAULT_PAGE_SIZE, MAX_PAGE_SIZE);
  // One row beyond the page tells us whether a next page exists without a count.
  const rows = await deps.briefs.list({
    limit: size + 1,
    ...(input.kind === undefined ? {} : { kind: input.kind }),
    ...(input.cursor === undefined ? {} : { cursor: input.cursor }),
  });
  const page = rows.slice(0, size);
  const nextCursor = rows.length > size ? (page.at(-1)?.id ?? null) : null;
  return { items: page.map(toBriefView), nextCursor };
}

export async function getBrief(deps: BriefDeps, id: string): Promise<BriefView | null> {
  const record = await deps.briefs.get(id);
  return record === null ? null : toBriefView(record);
}
